--------------------------------------------------------------------------------
-- 01_schema.sql — Standalone Authentication + Audit schema (Oracle)
--------------------------------------------------------------------------------
-- This is the SAMPLE database for the NodeExpress / CATHERINE template.
--
-- It is intentionally GENERIC and self-contained. Drop this into any fresh
-- Oracle schema and the template can authenticate, authorise (RBAC), and write
-- audit logs on its own.
--
-- Tables created:
--   T_USERS_DEV       — regular end-user accounts (Argon2id password hash)
--   T_ADMINS_DEV      — privileged accounts with RBAC + tamper-evident signature
--   T_AUDIT_LOGS_DEV  — request audit trail powering the Logging & Observability UI
--
-- NOT created here:
--   • Changelog / "version history" is an AES-256-GCM encrypted FILE store
--     (Backend/data/changelog.enc) — it needs no database table.
--   • Passwords are NOT seeded here. Argon2id hashes are salted + peppered with
--     ARGON2_PEPPER and rows are signed with DATA_SIGNING_SECRET, so valid rows
--     can only be produced by the app. Seed demo accounts with:
--         npm run db:seed:template
--
-- Prerequisites : Oracle Database 12c+ (XE 18c/21c is fine). IDENTITY columns
--                 and inline CHECK constraints require 12c or newer.
-- How to run    : connect as the schema owner, then:
--                   @01_schema.sql
--                   @02_seed_demo.sql        (optional sample audit data)
--                 or via SQL*Plus / SQLcl:
--                   sqlplus APP_USER/APP_PW@//host:1521/SERVICE @01_schema.sql
--
-- Idempotent    : the DROP guards below let you re-run this script safely.
--                 They IGNORE ORA-00942 (table does not exist) only.
--------------------------------------------------------------------------------

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- 0. RESET (safe re-run) — drops existing template tables if present.
--    Comment this block out if you want CREATE statements to fail on conflict.
--------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_SERVER_ALERT_ACK_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_SERVER_ALERT_LOG_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_AUDIT_LOGS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_ADMINS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_USERS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

--------------------------------------------------------------------------------
-- 1. T_USERS_DEV — regular (non-privileged) end-user accounts.
--------------------------------------------------------------------------------
-- The login identifier is USERNAME. PASSWORD stores an Argon2id hash produced by
-- CryptoVault.hashPassword() (never a plaintext or reversible value). A user with
-- no matching T_ADMINS_DEV row authenticates at USER level (userLevel = 1).
--------------------------------------------------------------------------------
CREATE TABLE T_USERS_DEV (
  ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USERNAME    VARCHAR2(100)  NOT NULL,
  PASSWORD    VARCHAR2(255)  NOT NULL,        -- Argon2id hash ($argon2id$...)
  FIRST_NAME  VARCHAR2(100),
  LAST_NAME   VARCHAR2(100),
  EMAIL       VARCHAR2(255),
  IS_ACTIVE   CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_USERS_DEV         PRIMARY KEY (ID),
  CONSTRAINT UQ_T_USERS_DEV_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_T_USERS_DEV_ACTIVE   CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  T_USERS_DEV              IS 'Template: regular end-user accounts (Argon2id hashed).';
COMMENT ON COLUMN T_USERS_DEV.USERNAME     IS 'Unique login identifier.';
COMMENT ON COLUMN T_USERS_DEV.PASSWORD     IS 'Argon2id hash from CryptoVault.hashPassword(). Never plaintext.';
COMMENT ON COLUMN T_USERS_DEV.IS_ACTIVE    IS 'Y = can log in; N = deactivated.';

--------------------------------------------------------------------------------
-- 2. T_ADMINS_DEV — privileged accounts with role-based access control (RBAC).
--------------------------------------------------------------------------------
-- ROLE drives the numeric userLevel used by AuthMiddleware.requireAccess():
--     SUPER_ADMIN -> 3, ADMIN -> 2, USER -> 1
-- SYSSIGNATURE is an HMAC-SHA256 hex digest (CryptoVault.signRecord('T_ADMINS_DEV', …))
-- over the security-relevant columns (USERNAME | PASSWORD | ROLE | IS_ACTIVE). It
-- is verified on every login; a mismatch means the row was tampered with directly
-- in the DB and the account is refused / downgraded to USER.
--------------------------------------------------------------------------------
CREATE TABLE T_ADMINS_DEV (
  ID                    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USERNAME              VARCHAR2(100)  NOT NULL,
  PASSWORD              VARCHAR2(255)  NOT NULL,   -- Argon2id hash ($argon2id$...)
  EMAIL                 VARCHAR2(255),             -- Server-notification delivery address
  ROLE                  VARCHAR2(20)   DEFAULT 'ADMIN' NOT NULL,
  IS_ACTIVE             CHAR(1)        DEFAULT 'Y' NOT NULL,
  -- Server Email Notifications — per-admin, per-channel opt-in (deny by default).
  -- Column ↔ channel mapping lives in AdminModel.SERVER_NOTIFY_FLAG_COLUMNS.
  CAN_RECEIVE_SRV_CRIT  CHAR(1)        DEFAULT 'N' NOT NULL,
  CAN_RECEIVE_SRV_DEPS  CHAR(1)        DEFAULT 'N' NOT NULL,
  CAN_RECEIVE_SRV_RED   CHAR(1)        DEFAULT 'N' NOT NULL,
  CAN_RECEIVE_SRV_SYS   CHAR(1)        DEFAULT 'N' NOT NULL,
  SYSSIGNATURE          VARCHAR2(64),              -- HMAC-SHA256 hex (tamper-evidence)
  CREATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT            TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_ADMINS_DEV          PRIMARY KEY (ID),
  CONSTRAINT UQ_T_ADMINS_DEV_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_T_ADMINS_DEV_ROLE     CHECK (ROLE IN ('SUPER_ADMIN', 'ADMIN', 'USER')),
  CONSTRAINT CK_T_ADMINS_DEV_ACTIVE   CHECK (IS_ACTIVE IN ('Y', 'N')),
  CONSTRAINT CK_T_ADMINS_DEV_SRV_CRIT CHECK (CAN_RECEIVE_SRV_CRIT IN ('Y', 'N')),
  CONSTRAINT CK_T_ADMINS_DEV_SRV_DEPS CHECK (CAN_RECEIVE_SRV_DEPS IN ('Y', 'N')),
  CONSTRAINT CK_T_ADMINS_DEV_SRV_RED  CHECK (CAN_RECEIVE_SRV_RED  IN ('Y', 'N')),
  CONSTRAINT CK_T_ADMINS_DEV_SRV_SYS  CHECK (CAN_RECEIVE_SRV_SYS  IN ('Y', 'N'))
);

COMMENT ON TABLE  T_ADMINS_DEV              IS 'Template: privileged accounts with RBAC and tamper-evident signature.';
COMMENT ON COLUMN T_ADMINS_DEV.ROLE         IS 'RBAC role: SUPER_ADMIN(3) | ADMIN(2) | USER(1).';
COMMENT ON COLUMN T_ADMINS_DEV.SYSSIGNATURE IS 'HMAC-SHA256 hex over signed columns. Verified at login.';
COMMENT ON COLUMN T_ADMINS_DEV.IS_ACTIVE    IS 'Y = can log in; N = deactivated (cannot log in or refresh).';
COMMENT ON COLUMN T_ADMINS_DEV.EMAIL        IS 'Delivery address for Server Email Notifications (NULL = never a recipient).';
COMMENT ON COLUMN T_ADMINS_DEV.CAN_RECEIVE_SRV_CRIT IS 'Opt-in: server-critical-notification channel.';
COMMENT ON COLUMN T_ADMINS_DEV.CAN_RECEIVE_SRV_DEPS IS 'Opt-in: server-dependencies-notification channel.';
COMMENT ON COLUMN T_ADMINS_DEV.CAN_RECEIVE_SRV_RED  IS 'Opt-in: server-red-metrics-notification channel.';
COMMENT ON COLUMN T_ADMINS_DEV.CAN_RECEIVE_SRV_SYS  IS 'Opt-in: server-system-notification channel.';

-- Recipient lookups are always "active admins opted in to one channel" — one
-- composite index per channel would be four near-duplicate indexes on a table
-- of tens of rows, so a single IS_ACTIVE index is deliberately enough here.
CREATE INDEX IX_ADMINS_ACTIVE ON T_ADMINS_DEV (IS_ACTIVE);

-- NOTE (signature scope): the CAN_RECEIVE_SRV_* flags are intentionally NOT part
-- of AdminModel.buildSignedFields(). Adding them would invalidate every existing
-- row's SYSSIGNATURE the moment the new code runs and block all admin logins
-- until each row is re-signed. If your deployment wants them tamper-evident,
-- add them to buildSignedFields() AND re-run `npm run db:seed:template` (or
-- re-sign every row) in the same release.

--------------------------------------------------------------------------------
-- 3. T_AUDIT_LOGS_DEV — per-request audit trail (Logging & Observability feature).
--------------------------------------------------------------------------------
-- Written asynchronously by AuditLogMiddleware after each response. Column set
-- MUST match AuditLogMiddleware._buildRecord(). STATUS_CATEGORY is the integer
-- status class ('2xx'..'5xx') used by the dashboard's golden-signal aggregates.
--------------------------------------------------------------------------------
CREATE TABLE T_AUDIT_LOGS_DEV (
  ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  REQUEST_ID        VARCHAR2(64),
  USER_ID           NUMBER,
  USERNAME          VARCHAR2(255),
  METHOD            VARCHAR2(10),
  ENDPOINT          VARCHAR2(1000),
  PARAMS            VARCHAR2(2000),
  STATUS_CODE       NUMBER(3),
  STATUS_CATEGORY   VARCHAR2(3),
  RESPONSE_TIME_MS  NUMBER,
  CLIENT_IP         VARCHAR2(64),
  SERVER_IP         VARCHAR2(64),
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_AUDIT_LOGS_DEV PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_AUDIT_LOGS_DEV                 IS 'Template: per-request audit trail powering the observability dashboard.';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.STATUS_CATEGORY IS 'Status class: 2xx | 3xx | 4xx | 5xx (used by golden-signal aggregates).';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.USER_ID         IS 'Numeric actor id; NULL/0 for anonymous requests.';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.PARAMS          IS 'Sanitised query params JSON (sensitive keys stripped, truncated to 2000).';

-- Indexes that match the model's access patterns:
--   • CREATED_AT DESC — list ordering + getLatestCreatedAt() (SSE poller)
--   • STATUS_CATEGORY — GROUP BY in the stats aggregate
--   • USER_ID         — unique-user GROUP BY in the stats aggregate
CREATE INDEX IX_AUDIT_CREATED_AT  ON T_AUDIT_LOGS_DEV (CREATED_AT DESC);
CREATE INDEX IX_AUDIT_STATUS_CAT  ON T_AUDIT_LOGS_DEV (STATUS_CATEGORY);
CREATE INDEX IX_AUDIT_USER_ID     ON T_AUDIT_LOGS_DEV (USER_ID);

--------------------------------------------------------------------------------
-- 4. T_SERVER_ALERT_LOG_DEV — alert / notification history (Server Email
--    Notifications feature).
--------------------------------------------------------------------------------
-- History and audit ONLY. The live "current alerts" list is always recomputed
-- from MetricsService.evaluateAlerts(); rows are appended by
-- AlertNotifierService on state TRANSITIONS and email outcomes — never on every
-- poll tick, or a steady-state alert would flood identical rows forever.
--
--   ALERT_KEY  — rule + identity, e.g. "HIGH_HEAP::global",
--                "ORACLE_POOL_SATURATION::appDb"; "critical-log" for the
--                critical channel (which has no per-identity state).
--   TRANSITION — FIRED      (OK → WARNING|CRITICAL, or a captured critical log)
--                ESCALATED  (WARNING → CRITICAL)
--                RENOTIFIED (cooldown re-notify at the same severity)
--                RECOVERED  (→ OK)
--                SUPPRESSED (critical storm ceiling hit; VALUE_NUM = count)
--   DETAILS    — sanitised JSON cause payload (AlertNotifierService redacts
--                password/token/secret/authorization/cookie keys, caps at 64 KB
--                and any embedded stack at 2000 chars).
--------------------------------------------------------------------------------
CREATE TABLE T_SERVER_ALERT_LOG_DEV (
  ID               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ALERT_KEY        VARCHAR2(200)  NOT NULL,
  RULE             VARCHAR2(64)   NOT NULL,
  SEVERITY         VARCHAR2(16)   NOT NULL,
  TRANSITION       VARCHAR2(16)   NOT NULL,
  VALUE_NUM        NUMBER,
  DESCRIPTION      VARCHAR2(1000),
  CHANNEL          VARCHAR2(64)   NOT NULL,
  NOTIFICATION_ID  VARCHAR2(64),
  EMAIL_STATUS     VARCHAR2(16)   NOT NULL,
  EMAIL_ERROR      VARCHAR2(1000),
  DETAILS          CLOB,
  CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_SERVER_ALERT_LOG_DEV PRIMARY KEY (ID),
  CONSTRAINT CK_SAL_SEVERITY     CHECK (SEVERITY IN ('WARNING', 'CRITICAL', 'RESOLVED')),
  CONSTRAINT CK_SAL_TRANSITION   CHECK (TRANSITION IN ('FIRED', 'ESCALATED', 'RENOTIFIED', 'RECOVERED', 'SUPPRESSED')),
  CONSTRAINT CK_SAL_EMAIL_STATUS CHECK (EMAIL_STATUS IN ('SENT', 'FAILED', 'SKIPPED', 'DISABLED')),
  CONSTRAINT CK_SAL_DETAILS_JSON CHECK (DETAILS IS JSON)
);

COMMENT ON TABLE  T_SERVER_ALERT_LOG_DEV            IS 'Template: server alert / notification history (append-only, transitions only).';
COMMENT ON COLUMN T_SERVER_ALERT_LOG_DEV.ALERT_KEY  IS 'rule::identity — e.g. HIGH_LATENCY::POST /api/v1/auth/login.';
COMMENT ON COLUMN T_SERVER_ALERT_LOG_DEV.DETAILS    IS 'Sanitised JSON cause payload (secrets redacted, size-capped).';

-- CREATED_AT DESC drives the default history page; (RULE, CREATED_AT DESC)
-- serves the per-rule filtered read.
CREATE INDEX IX_SAL_CREATED_AT   ON T_SERVER_ALERT_LOG_DEV (CREATED_AT DESC);
CREATE INDEX IX_SAL_RULE_CREATED ON T_SERVER_ALERT_LOG_DEV (RULE, CREATED_AT DESC);

--------------------------------------------------------------------------------
-- 5. T_SERVER_ALERT_ACK_DEV — currently acknowledged alerts.
--------------------------------------------------------------------------------
-- ONE row per alert that is acknowledged RIGHT NOW — not a history table (that
-- is T_SERVER_ALERT_LOG_DEV above). Upserted by acknowledge(), deleted by
-- unacknowledge(), by recovery (→ OK), by TTL expiry, and by escalation
-- override. AlertNotifierService.start() hydrates its in-memory ack map from
-- this table so a restart never loses an active ack.
--
-- Two safety nets, both enforced live on every poll tick, neither optional:
--   1. Escalation override — if live severity ranks HIGHER than SEVERITY_AT_ACK
--      the ack is cleared and the notification fires anyway. An ack can never
--      silently swallow a worsening incident.
--   2. TTL expiry — EXPIRES_AT = ACKED_AT + ALERT_ACK_TTL_HOURS (default 24).
--      No row lives forever unattended.
--------------------------------------------------------------------------------
CREATE TABLE T_SERVER_ALERT_ACK_DEV (
  ALERT_KEY        VARCHAR2(200)  NOT NULL,
  ACKED_BY         NUMBER         NOT NULL,   -- T_ADMINS_DEV.ID of the acknowledging admin
  ACKED_AT         TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  EXPIRES_AT       TIMESTAMP      NOT NULL,
  SEVERITY_AT_ACK  VARCHAR2(16)   NOT NULL,
  NOTE             VARCHAR2(500),
  CONSTRAINT PK_T_SERVER_ALERT_ACK_DEV PRIMARY KEY (ALERT_KEY),
  CONSTRAINT CK_SAA_SEVERITY CHECK (SEVERITY_AT_ACK IN ('WARNING', 'CRITICAL'))
);

COMMENT ON TABLE  T_SERVER_ALERT_ACK_DEV                 IS 'Template: currently acknowledged alerts (one row per live ack, not history).';
COMMENT ON COLUMN T_SERVER_ALERT_ACK_DEV.SEVERITY_AT_ACK IS 'Escalation baseline: a higher live severity auto-clears the ack.';
COMMENT ON COLUMN T_SERVER_ALERT_ACK_DEV.EXPIRES_AT      IS 'ACKED_AT + ALERT_ACK_TTL_HOURS; checked on every poll tick.';

--------------------------------------------------------------------------------
-- Done. Next:
--   • Seed demo accounts (Argon2id):  npm run db:seed:template
--   • (Optional) sample audit rows:   @02_seed_demo.sql
--------------------------------------------------------------------------------
