--------------------------------------------------------------------------------
-- 01_schema.sql — Standalone Authentication + Audit schema (Oracle)
--------------------------------------------------------------------------------
-- This is the SAMPLE database for the NodeExpress / CATHERINE template.
--
-- It is intentionally GENERIC and self-contained: it has NOTHING to do with the
-- HRIS (U_USERS / U_PERSONALINFOS) or Meal (T_EMP_MGMT_ADMIN / T_EMP_MASTER_LIST)
-- projects. Drop this into any fresh Oracle schema and the template can
-- authenticate, authorise (RBAC), and write audit logs on its own.
--
-- Tables created:
--   T_USERS_DEV       — regular end-user accounts (Argon2id password hash)
--   T_ADMINS_DEV      — privileged accounts with RBAC + tamper-evident signature
--   T_AUDIT_LOGS_DEV  — request audit trail powering the Logging & Observability UI
--
-- NOT created here:
--   • Changelog / "version history" is an AES-256-GCM encrypted FILE store
--     (Backend/data/changelog.enc) — it needs no database table.
--   • Passwords are NOT seeded here. Argon2id hashes are salted + peppered with
--     ARGON2_PEPPER and rows are signed with DATA_SIGNING_SECRET, so valid rows
--     can only be produced by the app. Seed demo accounts with:
--         npm run db:seed:template
--
-- Prerequisites : Oracle Database 12c+ (XE 18c/21c is fine). IDENTITY columns
--                 and inline CHECK constraints require 12c or newer.
-- How to run    : connect as the schema owner, then:
--                   @01_schema.sql
--                   @02_seed_demo.sql        (optional sample audit data)
--                 or via SQL*Plus / SQLcl:
--                   sqlplus APP_USER/APP_PW@//host:1521/SERVICE @01_schema.sql
--
-- Idempotent    : the DROP guards below let you re-run this script safely.
--                 They IGNORE ORA-00942 (table does not exist) only.
--------------------------------------------------------------------------------

SET DEFINE OFF;

--------------------------------------------------------------------------------
-- 0. RESET (safe re-run) — drops existing template tables if present.
--    Comment this block out if you want CREATE statements to fail on conflict.
--------------------------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_AUDIT_LOGS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_ADMINS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE T_USERS_DEV CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

--------------------------------------------------------------------------------
-- 1. T_USERS_DEV — regular (non-privileged) end-user accounts.
--------------------------------------------------------------------------------
-- The login identifier is USERNAME. PASSWORD stores an Argon2id hash produced by
-- CryptoVault.hashPassword() (never a plaintext or reversible value). A user with
-- no matching T_ADMINS_DEV row authenticates at USER level (userLevel = 1).
--------------------------------------------------------------------------------
CREATE TABLE T_USERS_DEV (
  ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USERNAME    VARCHAR2(100)  NOT NULL,
  PASSWORD    VARCHAR2(255)  NOT NULL,        -- Argon2id hash ($argon2id$...)
  FIRST_NAME  VARCHAR2(100),
  LAST_NAME   VARCHAR2(100),
  EMAIL       VARCHAR2(255),
  IS_ACTIVE   CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_USERS_DEV         PRIMARY KEY (ID),
  CONSTRAINT UQ_T_USERS_DEV_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_T_USERS_DEV_ACTIVE   CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  T_USERS_DEV              IS 'Template: regular end-user accounts (Argon2id hashed).';
COMMENT ON COLUMN T_USERS_DEV.USERNAME     IS 'Unique login identifier.';
COMMENT ON COLUMN T_USERS_DEV.PASSWORD     IS 'Argon2id hash from CryptoVault.hashPassword(). Never plaintext.';
COMMENT ON COLUMN T_USERS_DEV.IS_ACTIVE    IS 'Y = can log in; N = deactivated.';

--------------------------------------------------------------------------------
-- 2. T_ADMINS_DEV — privileged accounts with role-based access control (RBAC).
--------------------------------------------------------------------------------
-- ROLE drives the numeric userLevel used by AuthMiddleware.requireAccess():
--     SUPER_ADMIN -> 3, ADMIN -> 2, USER -> 1
-- SYSSIGNATURE is an HMAC-SHA256 hex digest (CryptoVault.signRecord('T_ADMINS_DEV', …))
-- over the security-relevant columns (USERNAME | PASSWORD | ROLE | IS_ACTIVE). It
-- is verified on every login; a mismatch means the row was tampered with directly
-- in the DB and the account is refused / downgraded to USER.
--------------------------------------------------------------------------------
CREATE TABLE T_ADMINS_DEV (
  ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  USERNAME      VARCHAR2(100)  NOT NULL,
  PASSWORD      VARCHAR2(255)  NOT NULL,       -- Argon2id hash ($argon2id$...)
  ROLE          VARCHAR2(20)   DEFAULT 'ADMIN' NOT NULL,
  IS_ACTIVE     CHAR(1)        DEFAULT 'Y' NOT NULL,
  SYSSIGNATURE  VARCHAR2(64),                  -- HMAC-SHA256 hex (tamper-evidence)
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_ADMINS_DEV          PRIMARY KEY (ID),
  CONSTRAINT UQ_T_ADMINS_DEV_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CK_T_ADMINS_DEV_ROLE     CHECK (ROLE IN ('SUPER_ADMIN', 'ADMIN', 'USER')),
  CONSTRAINT CK_T_ADMINS_DEV_ACTIVE   CHECK (IS_ACTIVE IN ('Y', 'N'))
);

COMMENT ON TABLE  T_ADMINS_DEV              IS 'Template: privileged accounts with RBAC and tamper-evident signature.';
COMMENT ON COLUMN T_ADMINS_DEV.ROLE         IS 'RBAC role: SUPER_ADMIN(3) | ADMIN(2) | USER(1).';
COMMENT ON COLUMN T_ADMINS_DEV.SYSSIGNATURE IS 'HMAC-SHA256 hex over signed columns. Verified at login.';
COMMENT ON COLUMN T_ADMINS_DEV.IS_ACTIVE    IS 'Y = can log in; N = deactivated (cannot log in or refresh).';

--------------------------------------------------------------------------------
-- 3. T_AUDIT_LOGS_DEV — per-request audit trail (Logging & Observability feature).
--------------------------------------------------------------------------------
-- Written asynchronously by AuditLogMiddleware after each response. Column set
-- MUST match AuditLogMiddleware._buildRecord(). STATUS_CATEGORY is the integer
-- status class ('2xx'..'5xx') used by the dashboard's golden-signal aggregates.
--------------------------------------------------------------------------------
CREATE TABLE T_AUDIT_LOGS_DEV (
  ID                NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  REQUEST_ID        VARCHAR2(64),
  USER_ID           NUMBER,
  USERNAME          VARCHAR2(255),
  METHOD            VARCHAR2(10),
  ENDPOINT          VARCHAR2(1000),
  PARAMS            VARCHAR2(2000),
  STATUS_CODE       NUMBER(3),
  STATUS_CATEGORY   VARCHAR2(3),
  RESPONSE_TIME_MS  NUMBER,
  CLIENT_IP         VARCHAR2(64),
  SERVER_IP         VARCHAR2(64),
  CREATED_AT        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_T_AUDIT_LOGS_DEV PRIMARY KEY (ID)
);

COMMENT ON TABLE  T_AUDIT_LOGS_DEV                 IS 'Template: per-request audit trail powering the observability dashboard.';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.STATUS_CATEGORY IS 'Status class: 2xx | 3xx | 4xx | 5xx (used by golden-signal aggregates).';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.USER_ID         IS 'Numeric actor id; NULL/0 for anonymous requests.';
COMMENT ON COLUMN T_AUDIT_LOGS_DEV.PARAMS          IS 'Sanitised query params JSON (sensitive keys stripped, truncated to 2000).';

-- Indexes that match the model's access patterns:
--   • CREATED_AT DESC — list ordering + getLatestCreatedAt() (SSE poller)
--   • STATUS_CATEGORY — GROUP BY in the stats aggregate
--   • USER_ID         — unique-user GROUP BY in the stats aggregate
CREATE INDEX IX_AUDIT_CREATED_AT  ON T_AUDIT_LOGS_DEV (CREATED_AT DESC);
CREATE INDEX IX_AUDIT_STATUS_CAT  ON T_AUDIT_LOGS_DEV (STATUS_CATEGORY);
CREATE INDEX IX_AUDIT_USER_ID     ON T_AUDIT_LOGS_DEV (USER_ID);

--------------------------------------------------------------------------------
-- Done. Next:
--   • Seed demo accounts (Argon2id):  npm run db:seed:template
--   • (Optional) sample audit rows:   @02_seed_demo.sql
--------------------------------------------------------------------------------
