"use strict";

/**
 * @fileoverview Fail-fast boot guard — validates security-critical environment
 * variables before the server starts.
 *
 * WHAT THIS FILE DOES
 * Checks that all secret env vars have been rotated away from their template
 * placeholders and meet minimum length requirements. If any check fails in
 * production, the process exits immediately (fail closed). In development,
 * violations are logged as warnings.
 *
 * HOW IT WORKS
 * Called from server.js after dotenv.config() but before app/db require.
 * Each rule specifies: env var name, minimum length, and a list of known
 * placeholder values that must be replaced.
 *
 * @module bootGuard
 */

const { logger } = require("../utils/logger");

// ─── Known placeholder values (shipped in .env.example) ───────────────────────

const KNOWN_PLACEHOLDERS = [
    "your-jwt-secret-here-change-in-production",
    "your-csrf-secret-key-here-change-in-production",
    "autogeneratedsecretchangeinproduction",
    "replace_this_with_a_64_char_hex_string_generated_by_the_command_above",
];

/**
 * Normalise a value for placeholder comparison.
 * Strips whitespace and lowercases so minor formatting differences don't
 * bypass the check.
 *
 * @param {string} val
 * @returns {string}
 */
function normalise(val) {
    return String(val)
        .replace(/[\s_-]/g, "")
        .toLowerCase();
}

/**
 * Secret validation rules.
 * Each entry: { env, minLength, label }
 *   - env:       process.env key name
 *   - minLength: minimum acceptable length (32 = 128-bit entropy minimum)
 *   - label:     human-readable name for error messages
 */
const SECRET_RULES = [
    { env: "JWT_SECRET", minLength: 32, label: "JWT signing secret" },
    { env: "CSRF_SECRET", minLength: 32, label: "CSRF secret" },
    { env: "COOKIE_SECRET", minLength: 32, label: "Cookie signing secret" },
    { env: "ARGON2_PEPPER", minLength: 32, label: "Argon2 pepper" },
    { env: "DATA_SIGNING_SECRET", minLength: 32, label: "Data signing secret" },
    {
        env: "CHANGELOG_ENCRYPTION_KEY",
        minLength: 32,
        label: "Changelog encryption key",
    },
];

/**
 * Validates all security-critical secrets at boot time.
 *
 * In production (NODE_ENV=production):
 *   - Any violation → process.exit(1) (fail closed)
 *
 * In development:
 *   - Violations are logged as warnings but do not halt the process
 *
 * @throws {never} Exits the process in production on failure.
 */
function validateSecrets() {
    const isProduction = process.env.NODE_ENV === "production";
    const violations = [];

    for (const rule of SECRET_RULES) {
        const value = process.env[rule.env];

        // Missing or empty
        if (!value || value.trim() === "") {
            violations.push(`${rule.label} (${rule.env}): not set or empty`);
            continue;
        }

        // Too short
        if (value.length < rule.minLength) {
            violations.push(
                `${rule.label} (${rule.env}): too short (${value.length} chars, minimum ${rule.minLength})`,
            );
            continue;
        }

        // Matches a known placeholder
        const normVal = normalise(value);
        if (KNOWN_PLACEHOLDERS.some((p) => normalise(p) === normVal)) {
            violations.push(
                `${rule.label} (${rule.env}): still using the template placeholder — rotate immediately`,
            );
        }
    }

    // ── DEMO_MODE + production guard (M4) ─────────────────────────────────────
    if (
        isProduction &&
        String(process.env.DEMO_MODE).toLowerCase() === "true"
    ) {
        violations.push(
            "DEMO_MODE=true is forbidden when NODE_ENV=production — disable demo mode or use a non-production environment",
        );
    }

    if (violations.length === 0) return; // all clear

    const header = `\n${"═".repeat(72)}\n  BOOT GUARD — ${violations.length} security violation(s) detected\n${"═".repeat(72)}`;
    const body = violations.map((v, i) => `  ${i + 1}. ${v}`).join("\n");
    const footer = `${"═".repeat(72)}\n`;

    if (isProduction) {
        // In production, use process.stderr directly — logger may not be fully
        // initialised yet, and we want this to be unmissable.
        process.stderr.write(
            `${header}\n${body}\n\n  Server REFUSED to start. Fix the above before deploying.\n${footer}\n`,
        );
        logger.crit("Boot guard failed — server refused to start", {
            violations,
        });
        process.exit(1);
    } else {
        // Development — warn loudly but allow startup for local convenience
        logger.warning(
            `Boot guard: ${violations.length} secret(s) using placeholder values — rotate before deploying`,
            { violations },
        );
    }
}

module.exports = { validateSecrets };
